/// <reference types="node" />
declare const errno: {
    [code in "ENOENT" | "UNKNOWN" | "OK" | "EOF" | "EADDRINFO" | "EACCES" | "EAGAIN" | "EADDRINUSE" | "EADDRNOTAVAIL" | "EAFNOSUPPORT" | "EALREADY" | "EBADF" | "EBUSY" | "ECONNABORTED" | "ECONNREFUSED" | "ECONNRESET" | "EDESTADDRREQ" | "EFAULT" | "EHOSTUNREACH" | "EINTR" | "EINVAL" | "EISCONN" | "EMFILE" | "EMSGSIZE" | "ENETDOWN" | "ENETUNREACH" | "ENFILE" | "ENOBUFS" | "ENOMEM" | "ENOTDIR" | "EISDIR" | "ENONET" | "ENOTCONN" | "ENOTSOCK" | "ENOTSUP" | "ENOSYS" | "EPIPE" | "EPROTO" | "EPROTONOSUPPORT" | "EPROTOTYPE" | "ETIMEDOUT" | "ECHARSET" | "EAIFAMNOSUPPORT" | "EAISERVICE" | "EAISOCKTYPE" | "ESHUTDOWN" | "EEXIST" | "ESRCH" | "ENAMETOOLONG" | "EPERM" | "ELOOP" | "EXDEV" | "ENOTEMPTY" | "ENOSPC" | "EIO" | "EROFS" | "ENODEV" | "ESPIPE" | "ECANCELED"]: (path?: string) => NodeJS.ErrnoException;
};
export default errno;
