name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deployment:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Build
        run: |
          yarn
          yarn workspace @screamingvoid/website build
          yarn workspace @screamingvoid/website export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/website/out
